/**
 * @description Action Type Constants
 */

export const CREATE_SERVER = 'CREATE_SERVER';
export const CREATE_STREAM = 'CREATE_STREAM';
export const LOG_MESSAGE = 'LOG_MESSAGE';
export const REMOVE_SERVER = 'REMOVE_SERVER';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';
export const SET_CURRENT_SERVER_ID = 'SET_CURRENT_SERVER_ID';
export const STOP_AND_REMOVE_SERVER = 'STOP_AND_REMOVE_SERVER';
export const UPDATE_SERVER_STATE = 'UPDATE_SERVER_STATE';
export const TOGGLE_PLANNED_RESPONSE = 'TOGGLE_PLANNED_RESPONSE';


